config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: "homes#index"
  get '/tour/:id' , to: "homes#tour", as: :tour_details
  resources :inquiries
  get '/all_tours', to: "homes#all_tours", as: :all_tours
  get '/search', to: "homes#search", as: :search
  get '/filter', to: "homes#filter", as: :filter
  get '/pages/:id', to: "homes#pages", as: :pages
  get '/leavemessage', to: "homes#leavemessage", as: :leavemessage

  devise_for :admin_user, path: 'admin/', controllers: {
    unlocks: 'devise/unlocks',
    passwords: 'devise/passwords',
    sessions: 'admin/sessions',
  }

  devise_scope :admin_user do
      namespace :admin do
        resources :users, only: %i[edit show update]
        resources :countries
        resources :regions
        resources :tours
        resources :pages
        resources :inquiries
        resources :trip_ideas
      end
    unauthenticated do
      # root 'devise/sessions#new', as: :unauthenticated_root
    end
  end    
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  enum role: {
    admin: 1,
    super_admin: 2,
    customer_service: 3,
    marketing: 4,
    operations: 5
  }, _prefix: true
  # Include default devise modules. Others available are:
# :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::ActiveStorage

  attr_accessor :data

  has_one_attached :storage_data
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_content
    rails_representation_url(storage_data.variant(resize: '800>').processed, only_path: true)
  end

  def url_thumb
    rails_representation_url(storage_data.variant(resize: '118x100').processed, only_path: true)
  end
end

app/models/country.rb
class Country < ApplicationRecord
    has_many :tours, dependent: :delete_all
    belongs_to :region, optional: true
    scope :active, -> { where( active: true ) }
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    belongs_to :tour, optional: true
    belongs_to :trip_idea, optional: true
    enum title: { Mr: 0, Mrs: 1, Ms: 2, Other:3 }
    enum user_type: { Customer:0, Agent: 1 }
    enum contact_method:  { Email:0, Phone: 1 }
end

app/models/page.rb
class Page < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    scope :active, -> { where( active: true ) }

    private

    def should_generate_new_friendly_id?
        slug.blank? || name_changed?
    end
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :countries, dependent: :nullify
    scope :active, -> { where( active: true ) }
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_many_attached :images
    has_one_attached :cover_image
    belongs_to :country
    belongs_to :trip_idea
    scope :featured, -> { where( featured: true ) }
    self.per_page = 2
end

app/models/trip_idea.rb
class TripIdea < ApplicationRecord
    scope :active, -> { where( active: true ) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource
    
    protected

    def layout_by_resource
        if devise_controller? && admin_user_signed_in?
            "layouts/devise"
        else
            "application"
        end
    end

    def authenticate_admin_user!
      if admin_user_signed_in?
        super
      else
        redirect_to new_admin_user_session_path
      end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
        @tours = Tour.featured.limit(12)
        @page = Page.new
        render "homes/index"
    end

    def tour
        @tour = Tour.find(params[:id])
        render 'homes/tour'
    end

    def all_tours
        if params['country']
            @country = Country.find_by(name: params['country'])
            if @country.present?
                @tours = @country.tours.paginate(page: params[:page],  per_page: 15)
            else
                @msg = 'No Tours Found'
            end
        else
            @tours = Tour.paginate(page: params[:page],  per_page: 15)
        end
        render 'homes/all_tours'
    end

    def search
        if params[:country].present?
            @country = Country.find_by(name: params[:country])
            @tours = @country.tours.where("destination_name ILIKE ? OR description ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").paginate(page: params[:page],  per_page: 15)
        else
            @tours = Tour.where("destination_name ILIKE ? OR description ILIKE ?", "%#{params[:query]}%", "%#{params[:query]}%").paginate(page: params[:page],  per_page: 15)
        end
        render 'homes/all_tours'
    end

    def filter
        @country = Country.find_by(name: params[:country])
        @tours = @country.tours
        if params[:price].present?
            @price = params[:price]
            price = params[:price].split('-')
            @tours =  @tours.where("price > ? OR price < ?", "#{price[0]}" , "#{price[1]}")
        end
        
        if params[:duration].present?
            @duration = params[:duration]
            duration = params[:duration].split('-')
            @tours =  @tours.where("duration > ? OR duration < ?", "#{duration[0]}" , "#{duration[1]}")
        end

        @tours = @tours.paginate(page: params[:page],  per_page: 15)
        render 'homes/all_tours'
    end

    def pages
        @page = Page.friendly.find(params['id'])
        render 'homes/page'
    end

    def leavemessage
        render 'homes/message'
    end
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
    def create
        @inquirey = Inquiry.new(permitted_params)
        if @inquirey.save
            flash['success'] = "We have recieved your inquiry, w'll get back to you soon, Thanks"
        else
            flash['error'] = "Unexpected error occured"                
        end
        redirect_to @inquirey.tour_id.present? ? tour_details_path(@inquirey.tour_id) : leavemessage_path
    end

    private

    def permitted_params
        params.permit(:first_name, :last_name, :title, :price, :customer_type, :country, :phone, :trip_idea_id, :email, :contact_method, :no_of_passenger, :departure_date, :description, :tour_id)
    end
end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/pages/_form.html.erb
<%= form_for [:admin, @page] do |form| %>

    <div class="form-group">
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control", placeholder: "Page Name" %>
    </div>

    <div class="form-group">
    <%= form.label :content %><br>
    <%= form.cktext_area :content, class: "form-control", placeholder: "Content" %>
    </div>

  <div class="form-group">
    <%= form.label :active, 'Active', class: 'form-label' %><br/>
    <%= form.select(:active, options_for_select([['True', true], ['False', false]], {selected: :active}),   {}, { class: 'form-control'})  %>
   </div>


    <div>
      <%= form.submit class: "btn btn-primary mt-2" %>
    </div>
  <% end %>

app/views/admin/pages/edit.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>Pages</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">Edit Page</h5>
        </div>
        <div class="card-body">
        <%= render partial: 'form'  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/pages/index.html.erb
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
    <%= render 'shared/messages' %>
      <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin /</span> Page</h4>

      <%= link_to 'New Page', new_admin_page_path,class: 'btn btn-primary mb-3  ' %></td>
      <div class="card">
        <h5 class="card-header">Pages</h5>
        <div class="table-responsive text-nowrap">

          <table class="table" id="dataTable">
            <thead>
              <tr>
                <th>Sr.No</th>
                <th>Page</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                <% @pages.each_with_index do |page, index| %>
                <tr>
                    <td><%= index+1 %>  </td>
                    <td><%= page.name %>  </td>
                    <td><span class="badge bg-label-info me-1"><%= page.active %>  </span></td>
                    <td class="d-flex">
                    <%= button_to "Edit",  edit_admin_page_path(page), method: :get,  class: "btn btn-primary btn-sm"  %>
                    <%= button_to "Delete",  admin_page_path(page), method: :delete, class: "btn btn-warning btn-sm"  %>
                    </td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
   
   
    </div>

app/views/admin/pages/new.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>Page</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">New Page</h5>
        </div>
        <div class="card-body">
        <%= render partial: 'form'  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin/_footer.html.erb
<!-- Core JS -->
<!-- build:js assets/vendor/js/core.js -->
<script src="/admin-assets/vendor/libs/jquery/jquery.js"></script>
<script src="/admin-assets/vendor/libs/popper/popper.js"></script>
<script src="/admin-assets/vendor/js/bootstrap.js"></script>
<script src="/admin-assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

<script src="/admin-assets/vendor/js/menu.js"></script>
<!-- endbuild -->

<!-- Vendors JS -->

<!-- Main JS -->
<script src="/admin-assets/js/main.js"></script>

<!-- Page JS -->

<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>
<script>

$(document).ready( function () {
    $('#dataTable').DataTable();
} );
</script>


</body>
</html>

app/views/layouts/admin/_header.html.erb
<html
  lang="en"
  class="light-style layout-menu-fixed"
  dir="ltr"
  data-theme="theme-default"
  data-assets-path="../assets/"
  data-template="vertical-menu-template-free"
>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"
    />

    <title></title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
      rel="stylesheet"
    />

    <!-- Icons. Uncomment required icon fonts -->

    <!-- Core CSS -->
    <link rel="stylesheet" href="/admin-assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="/admin-assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="/admin-assets/css/demo.css" />
    <link rel="stylesheet" href="/admin-assets/vendor/fonts/boxicons.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="/admin-assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->

    <!-- Helpers -->
    <script src="/admin-assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="/admin-assets/js/config.js"></script>
    <%= javascript_include_tag Ckeditor.cdn_url %>
    <script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
  </head>

  <body>

app/views/layouts/admin/_navbar.html.erb
          <nav
          class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
          id="layout-navbar"
        >
          <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
            <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
              <i class="bx bx-menu bx-sm"></i>
            </a>
          </div>

          <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
            <!-- Search -->
            <div class="navbar-nav align-items-center">
              <div class="nav-item d-flex align-items-center">
                <i class="bx bx-search fs-4 lh-0"></i>
                <input
                  type="text"
                  class="form-control border-0 shadow-none"
                  placeholder="Search..."
                  aria-label="Search..."
                />
              </div>
            </div>
            <!-- /Search -->

            <ul class="navbar-nav flex-row align-items-center ms-auto">
           

              <!-- User -->
              <li class="nav-item navbar-dropdown dropdown-user dropdown">
                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                  <div class="avatar avatar-online">
                    <img src="https://img.icons8.com/color/2x/user.png" alt class="w-px-40 h-auto rounded-circle" />
                  </div>
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                  <li>
                    <a class="dropdown-item" href="#">
                      <div class="d-flex">
                        <div class="flex-shrink-0 me-3">
                          <div class="avatar avatar-online">
                            <img src="https://img.icons8.com/color/2x/user.png" alt class="w-px-40 h-auto rounded-circle" />
                          </div>
                        </div>
                        <div class="flex-grow-1">
                          <span class="fw-semibold d-block"><%= current_admin_user.email %></span>
                          <small class="text-muted">Admin</small>
                        </div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <div class="dropdown-divider"></div>
                  </li>
                  <li>
                    <a class="dropdown-item" href="/admin/users/edit">
                      <i class="bx bx-user me-2"></i>
                      <span class="align-middle">My Profile</span>
                    </a>
                  </li>
                  <li>
                    <div class="dropdown-divider"></div>
                  </li>


                  <li class="dropdown-item">
                  <%= button_to destroy_admin_user_session_path, method: :delete, class: 'btn btn-primary' do %>
                    <i class="bx bx-power-off me-2"></i>
                    <span class="align-middle">Log Out</span>
                    <% end %>
                  </li>


                </ul>
              </li>
              <!--/ User -->
            </ul>
          </div>
        </nav>

app/views/layouts/admin/_navigation.html.erb
<div class="layout-wrapper layout-content-navbar">
    <div class="layout-container">
      <!-- Menu -->

      <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
        <div class="app-brand demo">
          <a href="#" class="app-brand-link">
            <span class="app-brand-logo demo d-block align-items-center justify-content-center">
                <%= image_tag "logo.png", class:"ms-4", width: "110px" %>
            </span>
          </a>

          <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
            <i class="bx bx-chevron-left bx-sm align-middle"></i>
          </a>
        </div>

        <div class="menu-inner-shadow"></div>

        <ul class="menu-inner py-1">


        <li class="menu-item ">
        <%= link_to admin_regions_path, class: 'menu-link' do %>
            <i class="menu-icon tf-icons bx bx-home-circle"></i>
            <div data-i18n="Analytics">Manage Regions</div>
          <% end %>
        </li>

        <li class="menu-item ">
        <%= link_to admin_trip_ideas_path, class: 'menu-link' do %>
            <i class="menu-icon tf-icons bx bx-water"></i>
            <div data-i18n="Analytics">Manage Trip Ideas</div>
          <% end %>
        </li>

        <li class="menu-item">
        <%= link_to admin_countries_path, class: 'menu-link' do %>
            <i class="menu-icon tf-icons bx bx-dock-top"></i>
            <div data-i18n="Analytics">Manage Countries</div>
          <% end %>
        </li>

        <li class="menu-item ">
        <%= link_to admin_tours_path, class: 'menu-link' do %>
            <i class="menu-icon tf-icons bx bx-cube-alt"></i>
            <div data-i18n="Analytics">Manage Tours</div>
          <% end %>
        </li>

        <li class="menu-item ">
        <%= link_to admin_inquiries_path, class: 'menu-link' do %>
            <i class="menu-icon tf-icons bx bx-box"></i>
            <div data-i18n="Analytics">Manage Inquiries</div>
          <% end %>
        </li>

        <li class="menu-item ">
        <%= link_to admin_pages_path, class: 'menu-link' do %>
            <i class="menu-icon tf-icons bx bx-dock-top"></i>
            <div data-i18n="Analytics">Manage Pages</div>
          <% end %>
        </li>


        </ul>
          </li>
      
      
    

         
        </ul>
      </aside>
      <!-- / Menu -->

      <!-- Layout container -->
      <div class="layout-page">

app/views/layouts/admin/application.html.erb
<%= render 'layouts/admin/header' %>
<%= render 'layouts/admin/navigation' %>
<%= render 'layouts/admin/navbar' %>'
<%= yield %>
<%= render 'layouts/admin/footer' %>

app/views/layouts/admin/devise.html.erb
<%= render 'layouts/admin/header' %>
<%= yield %>
<%= render 'layouts/admin/footer' %>

app/views/shared/_filters.html.erb
        <div class="customCard heightAuto p-3">
          <h3 class="headingTwo  d-none d-lg-block mt-4">Filters</h3>

          <div class="filters" id="filters">
            <%= form_with(url: filter_path, method: :get) do |form| %>

            <div class="form-group">
              <%= form.label :country %><br>
              <%= form.select(:country, options_for_select(Country.active.map{|c|[c.name, c.name]}), { prompt: "Select Country" }, { :class => 'form-control', :required => true }) %>
            </div><br>

            <div class="form-group">
              <%= form.label :duration %>(Days) <br>
              <%= form.select(:duration, options_for_select(['10-30','30-60','60-90'], @duration), { prompt: "Select Duration (Days)" }, { :class => 'form-control' }) %>
            </div><br>

              <div class="form-group">
              <%= form.label :price %> (USD)<br>
              <%= form.select(:price, options_for_select(['1000-3000','3000-6000','6000-9000'], @price), { prompt: "Select Price Range" }, { :class => 'form-control' }) %>
            </div>
            
            <%= form.submit  class: 'bannerBtn w-100 d-block', value: 'Apply' %>
            <% end %>

          </div>
        </div>

app/views/shared/_inquiry_form.html.erb
<%= form_with(url: inquiries_path, method: :post) do |form| %>

<div class="form px-3 px-md-5">
  <div class="row py-5">
    <div class="col-md-12">
      <p class="small justify">Please note * denotes fields that are mandatory and must be filled out in order to be processed. Thank you</p>
    </div>
  </div>
  <div class="row mb-2">
    <div class="col-md-6">
      <p class="m-0 small">Title</p>
    </div>
    <div class="col-md-6">
    <%= form.select(:title, Inquiry.titles.keys.map {|title| [title.titleize,title]}, {}, class: 'w-100 selectBorder')%>
    </div>
  </div>

 <% if tour.present? %>
  <%= form.hidden_field :tour_id, value: tour.id %>
<% end %>
  <div class="row mb-2">
    <div class="col-md-6 small">
      <%= form.label :first_name %>*<br>
    </div>
    <div class="col-md-6">
      <%= form.text_field :first_name, class: "w-100 selectBorder", required: true %>
    </div>
  </div>


  <div class="row mb-2">
  <div class="col-md-6 small">
    <%= form.label :last_name %>*<br>
  </div>
  <div class="col-md-6">
    <%= form.text_field :last_name, class: "w-100 selectBorder", required: true %>
  </div>
</div>


  <div class="row mb-2">
    <div class="col-md-6 small">
      <%= form.label :Destination %><br>
    </div>
    <div class="col-md-6">
     <%= form.text_field :country, class: "w-100 selectBorder" %>
     </div>
  </div>


 <div class="row mb-2">
    <div class="col-md-6 small">
      <%= form.label :desired_price %><br>
    </div>
    <div class="col-md-6">
     <%= form.text_field :price, class: "w-100 selectBorder" %>
     </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6 small">
      <%= form.label :trip_idea_id %>*<br>
    </div>
    <div class="col-md-6">
        <%= form.select(:trip_idea_id, options_for_select(TripIdea.active.map{|c|[c.name, c.id]}), { prompt: 'Select Trip idea' }, { :class => 'form-control' }) %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6 small">
      <%= form.label :phone %>*<br>
    </div>
    <div class="col-md-6">
      <%= form.text_field :phone, class: "w-100 selectBorder", required: true %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6 small">
      <%= form.label :email %>*<br>
    </div>
    <div class="col-md-6">
      <%= form.email_field :email, class: "w-100 selectBorder", required: true %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <p class="m-0 small">How should we contact you?*</p>
    </div>
    <div class="col-md-6">
    <%= form.select(:contact_method, options_for_select([['Email'], ['Phone']], {selected: :active}),   {}, { class: 'form-control'})  %>
    </div>
  </div>

  <div class="row mb-2">
    <div class="col-md-6">
      <p class="m-0 small">Number of passengers*</p>
    </div>
    <div class="col-md-6">
    <%= form.number_field :no_of_passenger, min:1, class: "w-100 selectBorder" %>
    </div>
  </div>


  <div class="row mb-2">
    <div class="col-md-6">
      <p class="m-0 small">Date of departure*</p>
    </div>
    <div class="col-md-6">
    <%= form.date_select :departure_date, {}, min: Date.today, class: "selectBorder" %> 
    </div>
  </div>


  <div class="row mb-2">
    <div class="col-md-12">
      <p class="small">Tell us more about how we can help:</p>
    </div>
    <div class="col-md-12">
      <%= form.text_area :description, class: "selectBorder w-100" %> 
    </div>
  </div>

  <div class="row pb-4 mb-2">
    <div class="col-md-12">
      <p class="small justify">Get travel tips and ideas, offers, and contests delivered to your inbox.  We guarantee 100% privacy. Your information will not be shared, and you can unsubscribe at any time.</p>
    </div>


    <div class="col-md-6">
      </div>
    <div class="col-md-6">         
    <%= form.submit class: "inquiryBtn w-100 mt-3" %>              
    </div>
  </div>

</div>

<% end %>

app/views/shared/_messages.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %> alert-dismissible">
  <%= value %>
</div>
<% end %>

app/views/shared/_search.html.erb
<section class="finderForm" id="search">

<%= form_with url: "/search", method: :get do |form| %>
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-3 mt-2 mt-md-0">
        <div class="feildDiv">
          <i class="fa-solid fa-globe"></i> 
          <%= form.select(:country, options_for_select(Country.active.map{|c|[c.name, c.name]}, params[:country]), { prompt: "Select Country" },  { :class => 'js-example-basic-single w-100 select2 destSelect"' }) %>   
        </div>
      </div>
      <div class="col-sm-10 col-md-6 mt-2 mt-md-0">
      
      <div class="feildDiv">
        <%= form.text_field :query, class: "form-control", value: params[:query] %>
        </div>
      </div>

      <div class="col-sm-6 col-md-3 mt-2 mt-md-0 ">
        <button class="findBtn">Find My Trip!</button>
      </div>
    </div>
  </div>

<% end %>
</section>

app/views/shared/_tour.html.erb
<div class="customCardOne" style="min-height:577px">
<div class="cardTop">

<%= link_to tour_details_path(tour) do %>
  <% if tour.cover_image.attached? %>
  <%= image_tag tour.cover_image, class: "img-fluid", style: "max-height:240px !important;" %>
  <% end %>
<% end %>
</div>
<div class="cardBottom p-2">
  <h3 class="headingTwo m-0"><%= tour.country.name %></h3>
  <p class="medium textJustify small"> <b><%= tour.destination_name %> </b></p>
  <p class="small textJustify"><%= tour.short_description %></p>
</div>

<div class="button p-2 d-flex justify-content-end">
<%= link_to tour_details_path(tour), class: 'detailsBtn' do %>
    <span>See Details </span>
    <i class="fa-solid fa-circle-arrow-right"></i> 
  <% end %>
</div>


</div>