config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: "homes#index"
  get '/tour/:id' , to: "homes#tour", as: :tour_details
  resources :inquiries
  get '/all_tours', to: "homes#all_tours", as: :all_tours
  get '/search', to: "homes#search", as: :search
  get '/filter', to: "homes#filter", as: :filter
  get '/pages/:id', to: "homes#pages", as: :pages
  get '/leavemessage', to: "homes#leavemessage", as: :leavemessage

  devise_for :admin_user, path: 'admin/', controllers: {
    unlocks: 'devise/unlocks',
    passwords: 'devise/passwords',
    sessions: 'admin/sessions',
  }

  devise_scope :admin_user do
      namespace :admin do
        resources :users, only: %i[edit show update]
        resources :countries
        resources :regions
        resources :tours
        resources :pages
        resources :inquiries
        resources :trip_ideas
      end
    unauthenticated do
      # root 'devise/sessions#new', as: :unauthenticated_root
    end
  end    
end

app/models/tour.rb
class Tour < ApplicationRecord
    has_many_attached :images
    has_one_attached :cover_image
    belongs_to :country
    belongs_to :trip_idea
    scope :featured, -> { where( featured: true ) }
    self.per_page = 2
end

app/controllers/admin/tours_controller.rb
module Admin
    class ToursController < AdminController
        before_action :set_tour, only: %i[edit update destroy show] 
        before_action :authenticate_admin_user!

        def index
            @tours = Tour.order(:id)
        end

        def new
            @tour = Tour.new
        end

        def create
            @tour = Tour.new(permitted_params)
            if @tour.save!
                flash['success'] ="#{@tour.destination_name} has saved successfully"
            else
                flash['error'] ="Unexpected error occured"                
            end
            redirect_to admin_tours_path
        end

        def edit
        end

        def update
            if @tour.update(permitted_params)
                flash['success'] ="#{@tour.destination_name} has updated successfully"
                redirect_to admin_tours_path
            else
                flash['error'] = "Unexpected error occured"
                redirect_to @tour
            end
        end

        def destroy
            if @tour.destroy
                flash['success'] ="#{@tour.destination_name} has deleted successfully"
                redirect_to admin_tours_path
            else
                flash['error'] = "Unexpected error occured"
                redirect_to @tour
            end
        end

        private

        def permitted_params
            params.require(:tour).permit(:destination_name, :description, :short_description, :duration, :price, :cover_image, :featured, :trip_idea_id, :country_id, images: [])
        end

        def set_tour
            @tour = Tour.find(params[:id])
        end
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/admin/tours/_form.html.erb
<%= form_for [:admin, @tour] do |form| %>

    <div class="form-group">
    <%= form.label :country_id %><br>
    <%= form.select(:country_id, options_for_select(Country.active.map{|c|[c.name, c.id]}, { selected: @tour.country&.id }), {}, { :class => 'form-control' }) %>
    </div>

    <div class="form-group">
    <%= form.label :trip_idea_id %><br>
    <%= form.select(:trip_idea_id, options_for_select(TripIdea.active.map{|c|[c.name, c.id]}, { selected: @tour&.trip_idea_id }), {}, { :class => 'form-control' }) %>
    </div>

    <div class="form-group">
      <%= form.label :destination_name %><br>
      <%= form.text_field :destination_name, class: "form-control", placeholder: "Destination" %>
    </div>

    <div class="form-group">
      <%= form.label :short_description %> Max 250 characters <br>
      <%= form.text_field :short_description, class: "form-control", placeholder: "Short Description", maxlength: "250" %>
    </div>

    <div class="form-group">
    <%= form.label :description %><br>
    <%= form.cktext_area :description, class: "form-control", placeholder: "Description" %>
    </div>

    <div class="form-group">
    <%= form.label :price %><br>
    <%= form.number_field :price, class: "form-control", placeholder: "Price" %>
    </div>

    <div class="form-group">
    <%= form.label :duration %><br>
    <%= form.number_field :duration, class: "form-control", placeholder: "Duration" %>
    </div>

    <div class="form-group">
    <%= form.label :featured, 'Featured', class: 'form-label' %><br/>
    <%= form.select(:featured, options_for_select([['True', true], ['False', false]], {selected: :featured}),   {}, { class: 'form-control'})  %>
    </div>

    <div class="form-group">
    <%= form.label :cover_image %><br />
    <%= form.file_field :cover_image %>
    </div>

    <div class="form-group">
    <%= form.label :images %><br />
    <%= form.file_field :images, multiple: true %>
    </div>
  

    <div>
      <%= form.submit class: "btn btn-primary mt-2" %>
    </div>
  <% end %>

app/views/admin/tours/edit.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>Tours</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">Edit Tour</h5>
        </div>
        <div class="card-body">
        <%= render partial: 'form'  %>

        <%  @tour.images.each do |img| %>
            <td style="width:20px"><%= image_tag img, class: "img img-thumbnail" %></td>
           <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/admin/tours/index.html.erb
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
    <%= render 'shared/messages' %>
      <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin /</span> Tours</h4>

      <%= link_to 'New Tour', new_admin_tour_path,class: 'btn btn-primary mb-3  ' %></td>
      <div class="card">
        <h5 class="card-header">Tours</h5>
        <div class="table-responsive text-nowrap">

          <table class="table" id="dataTable">
            <thead>
              <tr>
                <th>Sr.No</th>
                <th>Desination</th>
                <th>Country</th>
                <th>Duration</th>
                <th>Price</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                <% @tours.each_with_index do |tour, index| %>
                <tr>
                    <td><%= index+1 %>  </td>
                    <td><%= tour.destination_name %>  </td>
                    <td><%= tour.country.name %>  </td>
                    <td><%= tour.duration %>  </td>
                    <td><%= tour.price %>  </td>
                    <td class="d-flex">

                    <%= button_to "Edit", edit_admin_tour_path(tour), method: :get, class: "btn btn-sm btn-primary"  %>
                    <%= button_to "Delete", admin_tour_path(tour), method: :delete, class: "btn btn-warning btn-sm"  %>
                    </td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
   
   
    </div>

app/views/admin/tours/new.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>Tours</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">New Tour</h5>
        </div>
        <div class="card-body">
        <%= render partial: 'form'  %>
        </div>
      </div>
    </div>
  </div>
</div>