config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: "homes#index"
  get '/tour/:id' , to: "homes#tour", as: :tour_details
  resources :inquiries
  get '/all_tours', to: "homes#all_tours", as: :all_tours
  get '/search', to: "homes#search", as: :search
  get '/filter', to: "homes#filter", as: :filter
  get '/pages/:id', to: "homes#pages", as: :pages
  get '/leavemessage', to: "homes#leavemessage", as: :leavemessage

  devise_for :admin_user, path: 'admin/', controllers: {
    unlocks: 'devise/unlocks',
    passwords: 'devise/passwords',
    sessions: 'admin/sessions',
  }

  devise_scope :admin_user do
      namespace :admin do
        resources :users, only: %i[edit show update]
        resources :countries
        resources :regions
        resources :tours
        resources :pages
        resources :inquiries
        resources :trip_ideas
      end
    unauthenticated do
      # root 'devise/sessions#new', as: :unauthenticated_root
    end
  end    
end

app/models/region.rb
class Region < ApplicationRecord
    has_many :countries, dependent: :nullify
    scope :active, -> { where( active: true ) }
end

app/controllers/admin/regions_controller.rb
module Admin
    class RegionsController < AdminController
        before_action :set_region, only: %i[edit update destroy]
        before_action :authenticate_admin_user!

        def index
            @regions = Region.all
        end

        def new
            @region = Region.new
        end

        def create
            @region =  Region.new(permitted_params)
            if @region.save
                flash['success'] ="#{@region.region_name} saved successfully"
            else
                flash['error'] ="Unexpected error occured"                
            end
            redirect_to admin_regions_path
        end

        def edit;end

        def update
            if @region.update(permitted_params)
                flash['success'] = "#{@region.region_name} updated successfully"
                redirect_to admin_regions_path
            else
                redirect_to @region
            end
        end
        
        def destroy
            if @region.destroy
                flash['success'] = "#{@region.region_name} Deleted successfully"
                redirect_to admin_regions_path
            else
                flash['errror'] = "Unexpected error occured"
                redirect_to admin_regions_path
            end
        end

        private

        def permitted_params
            params.require(:region).permit(:region_name, :active)
        end

        def set_region
            @region = Region.find(params['id'])
        end
    end
end

app/views/admin/regions/_form.html.erb
<%= form_for [:admin, @region] do |form| %>
    <div class="form-group">
      <%= form.label :name %><br>
      <%= form.text_field :region_name, class: "form-control" %>
    </div>

  <div class="form-group">
    <%= form.label :active, 'Active', class: 'form-label' %><br/>
    <%= form.select(:active, options_for_select([['True', true], ['False', false]], {selected: :active}),   {}, { class: 'form-control'})  %>
   </div>
  
    <div>
      <%= form.submit class: "btn btn-primary mt-2" %>
    </div>
  <% end %>

app/views/admin/regions/edit.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>Regions</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">Edit Region</h5>
        </div>
        <div class="card-body">
        <%= render partial: 'form'  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/regions/index.html.erb
<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
    <%= render 'shared/messages' %>
      <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin /</span> Regions</h4>

      <%= link_to 'New Region', new_admin_region_path,class: 'btn btn-primary mb-3  ' %></td>
      <div class="card">
        <h5 class="card-header">Region</h5>
        <div class="table-responsive text-nowrap">

          <table class="table" id="dataTable">
            <thead>
              <tr>
                <th>Sr.No</th>
                <th>Country</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody class="table-border-bottom-0">
                <% @regions.each_with_index do |region, index| %>
                <tr>
                    <td><%= index+1 %>  </td>
                    <td><%= region.region_name %>  </td>
                    <td><span class="badge bg-label-info me-1"><%= region.active %>  </span></td>
                    <td class="d-flex">
                    <%= button_to "Edit",  edit_admin_region_path(region), method: :get,  class: "btn btn-primary btn-sm"  %>
                    <%= button_to "Delete",  admin_region_path(region), method: :delete, class: "btn btn-warning btn-sm"  %>
                    </td>
                </tr>
                <% end %>
            </tbody>
          </table>
        </div>
      </div>
   
   
    </div>

app/views/admin/regions/new.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>Regions</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">New Region</h5>
        </div>
        <div class="card-body">
        <%= render partial: 'form'  %>
        </div>
      </div>
    </div>
  </div>
</div>