config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: "homes#index"
  get '/tour/:id' , to: "homes#tour", as: :tour_details
  resources :inquiries
  get '/all_tours', to: "homes#all_tours", as: :all_tours
  get '/search', to: "homes#search", as: :search
  get '/filter', to: "homes#filter", as: :filter
  get '/pages/:id', to: "homes#pages", as: :pages
  get '/leavemessage', to: "homes#leavemessage", as: :leavemessage

  devise_for :admin_user, path: 'admin/', controllers: {
    unlocks: 'devise/unlocks',
    passwords: 'devise/passwords',
    sessions: 'admin/sessions',
  }

  devise_scope :admin_user do
      namespace :admin do
        resources :users, only: %i[edit show update]
        resources :countries
        resources :regions
        resources :tours
        resources :pages
        resources :inquiries
        resources :trip_ideas
      end
    unauthenticated do
      # root 'devise/sessions#new', as: :unauthenticated_root
    end
  end    
end

app/models/trip_idea.rb
class TripIdea < ApplicationRecord
    scope :active, -> { where( active: true ) }
end

app/controllers/admin/trip_ideas_controller.rb
module Admin
  class TripIdeasController < AdminController
    before_action :set_trip_idea, only: %i[ show edit update destroy ]

    # GET /trip_ideas or /trip_ideas.json
    def index
      @trip_ideas = TripIdea.all
    end

    # GET /trip_ideas/1 or /trip_ideas/1.json
    def show
    end

    # GET /trip_ideas/new
    def new
      @trip_idea = TripIdea.new
    end

    # GET /trip_ideas/1/edit
    def edit
    end

    # POST /trip_ideas or /trip_ideas.json
    def create
      @trip_idea = TripIdea.new(trip_idea_params)  
      if @trip_idea.save
        flash['success'] ="#{@trip_idea.name} saved successfully"
      else
        flash['error'] ="Unexpected error occured"                
      end
      redirect_to admin_trip_ideas_path
    end

    def update
      if @trip_idea.update(trip_idea_params)
        flash['success'] ="#{@trip_idea.name} updated successfully"
      else
        flash['error'] ="Unexpected error occured"                
      end
      redirect_to admin_trip_ideas_path
    end

    # DELETE /trip_ideas/1 or /trip_ideas/1.json
    def destroy
      if @trip_idea.destroy
        flash['success'] ="#{@trip_idea.name} deleted successfully"
      else
        flash['error'] ="Unexpected error occured"                
      end
      redirect_to admin_trip_ideas_path
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_trip_idea
        @trip_idea = TripIdea.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def trip_idea_params
        params.require(:trip_idea).permit(:name, :active)
      end
  end
end

app/views/admin/trip_ideas/_form.html.erb
  <%= form_for [:admin, @trip_idea] do |form| %>
    <div class="form-group">
      <%= form.label :name %><br>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
    <%= form.label :active, 'Active', class: 'form-label' %><br/>
    <%= form.select(:active, options_for_select([['True', true], ['False', false]], { selected: @trip_idea.active } ), { }, { class: 'form-control'})  %>
   </div>
  
    <div>
      <%= form.submit class: "btn btn-primary mt-2" %>
    </div>
  <% end %>

app/views/admin/trip_ideas/edit.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>Trip Idea</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">Edit Trip Idea</h5>
        </div>
        <div class="card-body">
        <%= render partial: 'form'  %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/trip_ideas/index.html.erb
<%# <%= link_to 'New Trip Idea', new_trip_idea_path %> 


<div class="content-wrapper">
    <div class="container-xxl flex-grow-1 container-p-y">
    <%= render 'shared/messages' %>
      <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin /</span> Trip Ideas</h4>
      <%= link_to 'New Trip Idea', new_admin_trip_idea_path,class: 'btn btn-primary mb-3  ' %></td>
      <div class="card">
        <h5 class="card-header">Trip Ideas</h5>
        <div class="table-responsive text-nowrap">
        <table class="table" id="dataTable"> 
          <thead>
            <tr>
              <th>Name</th>
              <th>Active</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            <% @trip_ideas.each do |trip_idea| %>
              <tr>
                <td><%= trip_idea.name %></td>
                <td><span class="badge bg-label-info me-1"><%= trip_idea.active %></span></td>
                <td class="d-flex">
                  <%= button_to 'Edit', edit_admin_trip_idea_path(trip_idea),method: :get, class: "btn btn-primary btn-sm" %>
                  <%= button_to 'Destroy', admin_trip_idea_path(trip_idea), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning btn-sm" %>
                </td>
              </tr>
            <% end %>
          </tbody>
      </table>
        </div>
      </div>
   
   
    </div>

app/views/admin/trip_ideas/new.html.erb
<div class="content-wrapper">
<div class="container-xxl flex-grow-1 container-p-y">
  <h4 class="fw-bold py-3 mb-4"><span class="text-muted fw-light">Admin/</span>New Trip Idea</h4>

  <div class="row">
    <div class="col-md-8">
      <div class="card mb-4">
        <div class="card-header d-flex justify-content-between align-items-center">
          <h5 class="mb-0">New Trip Idea</h5>
        </div>
        <div class="card-body">
       <%= render 'form', trip_idea: @trip_idea %>

        </div>
      </div>
    </div>
  </div>
</div>